version: '3'

services:
  nodejs:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
    environment:
      - PORT=4000
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
